### ISSUE TITLE
empty command causes crash

### ISSUE THREAD

**Issue by CaiusAjiz** [CaiusAjiz/TimeSince#13]
demonstrated with `!timeSinceCreated` / `!tsc` but passing the bot an empty command causes it to asplode.

**Comment by SamThompson57** [comment]
args[0] would be null or undefined with nothing in it?. we could check for that an then send a text string of how to use said command

**Comment by CaiusAjiz** [comment]
basically yeah, I'm thinking once I've got #10 done, just have it spit out the help text for the command when `args[0]` be null.

**Comment by CaiusAjiz** [comment]
#16 closed this
